module.exports = {
  apps: [
    // ============================================
    // NestJS 服务
    // ============================================
    {
      name: 'user-service',
      cwd: './services/user-service',
      script: 'npm',
      args: 'run dev',
      env: {
        NODE_ENV: 'development',
        PORT: 60002,
        DB_HOST: 'localhost',
        DB_PORT: 60030,
        DB_USER: 'postgres',
        DB_PASSWORD: 'postgres',
        DB_NAME: 'lnk_users',
        JWT_SECRET: process.env.JWT_SECRET || 'GNS838yv/V8THLBmIBDSqeurqvPgTzNRHymb5q9wEa3FqV9ibtbZnHNfHFrwFQeU',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 60031,
      },
      watch: false,
      ignore_watch: ['node_modules', 'dist'],
    },
    {
      name: 'link-service',
      cwd: './services/link-service',
      script: 'npm',
      args: 'run dev',
      env: {
        NODE_ENV: 'development',
        PORT: 60003,
        DB_HOST: 'localhost',
        DB_PORT: 60030,
        DB_USER: 'postgres',
        DB_PASSWORD: 'postgres',
        DB_NAME: 'lnk_links',
        JWT_SECRET: process.env.JWT_SECRET || 'GNS838yv/V8THLBmIBDSqeurqvPgTzNRHymb5q9wEa3FqV9ibtbZnHNfHFrwFQeU',
        INTERNAL_API_KEY: process.env.INTERNAL_API_KEY || '7822d1d536c34796e41e10ff229cc531b28c31299191d2e07b4a7025f0d4c6c2',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 60031,
      },
      watch: false,
    },
    {
      name: 'qr-service',
      cwd: './services/qr-service',
      script: 'npm',
      args: 'run dev',
      env: {
        NODE_ENV: 'development',
        PORT: 60005,
      },
      watch: false,
    },
    {
      name: 'page-service',
      cwd: './services/page-service',
      script: 'npm',
      args: 'run dev',
      env: {
        NODE_ENV: 'development',
        PORT: 60006,
        DB_HOST: 'localhost',
        DB_PORT: 60030,
        DB_USER: 'postgres',
        DB_PASSWORD: 'postgres',
        DB_NAME: 'lnk_pages',
        JWT_SECRET: process.env.JWT_SECRET || 'GNS838yv/V8THLBmIBDSqeurqvPgTzNRHymb5q9wEa3FqV9ibtbZnHNfHFrwFQeU',
      },
      watch: false,
    },
    {
      name: 'deeplink-service',
      cwd: './services/deeplink-service',
      script: 'npm',
      args: 'run dev',
      env: {
        NODE_ENV: 'development',
        PORT: 60007,
        DB_HOST: 'localhost',
        DB_PORT: 60030,
        DB_USER: 'postgres',
        DB_PASSWORD: 'postgres',
        DB_NAME: 'lnk_deeplinks',
        JWT_SECRET: process.env.JWT_SECRET || 'GNS838yv/V8THLBmIBDSqeurqvPgTzNRHymb5q9wEa3FqV9ibtbZnHNfHFrwFQeU',
      },
      watch: false,
    },
    {
      name: 'campaign-service',
      cwd: './services/campaign-service',
      script: 'npm',
      args: 'run dev',
      env: {
        NODE_ENV: 'development',
        PORT: 60008,
        DB_HOST: 'localhost',
        DB_PORT: 60030,
        DB_USER: 'postgres',
        DB_PASSWORD: 'postgres',
        DB_NAME: 'lnk_campaigns',
        JWT_SECRET: process.env.JWT_SECRET || 'GNS838yv/V8THLBmIBDSqeurqvPgTzNRHymb5q9wEa3FqV9ibtbZnHNfHFrwFQeU',
      },
      watch: false,
    },
    {
      name: 'notification-service',
      cwd: './services/notification-service',
      script: 'npm',
      args: 'run dev',
      env: {
        NODE_ENV: 'development',
        PORT: 60010,
        REDIS_HOST: 'localhost',
        REDIS_PORT: 60031,
        SMTP_HOST: 'localhost',
        SMTP_PORT: 1025,
        SMTP_FROM: 'noreply@lnk.day',
      },
      watch: false,
    },
    {
      name: 'console-service',
      cwd: './services/console-service',
      script: 'npm',
      args: 'run dev',
      env: {
        NODE_ENV: 'development',
        PORT: 60001,
        DB_HOST: 'localhost',
        DB_PORT: 60030,
        DB_USER: 'postgres',
        DB_PASSWORD: 'postgres',
        DB_NAME: 'lnk_console',
        JWT_SECRET: process.env.JWT_SECRET || 'GNS838yv/V8THLBmIBDSqeurqvPgTzNRHymb5q9wEa3FqV9ibtbZnHNfHFrwFQeU',
        INTERNAL_API_KEY: process.env.INTERNAL_API_KEY || '7822d1d536c34796e41e10ff229cc531b28c31299191d2e07b4a7025f0d4c6c2',
        USER_SERVICE_URL: 'http://localhost:60002',
        LINK_SERVICE_URL: 'http://localhost:60003',
        ANALYTICS_SERVICE_URL: 'http://localhost:60020',
        QR_SERVICE_URL: 'http://localhost:60005',
        PAGE_SERVICE_URL: 'http://localhost:60006',
        DEEPLINK_SERVICE_URL: 'http://localhost:60007',
        NOTIFICATION_SERVICE_URL: 'http://localhost:60010',
        CAMPAIGN_SERVICE_URL: 'http://localhost:60008',
      },
      watch: false,
    },

    // ============================================
    // Go 服务
    // ============================================
    {
      name: 'redirect-service',
      cwd: '/home/eric/lnk.day/services/redirect-service',
      script: '/home/eric/lnk.day/services/redirect-service/redirect-service',
      interpreter: 'none',
      env: {
        PORT: '60004',
        LINK_SERVICE_URL: 'http://localhost:60003',
        INTERNAL_API_KEY: process.env.INTERNAL_API_KEY || '7822d1d536c34796e41e10ff229cc531b28c31299191d2e07b4a7025f0d4c6c2',
        REDIS_URL: 'redis://localhost:60031',
        KAFKA_BROKERS: 'localhost:60033',
        GEOIP_DB_PATH: './GeoLite2-City.mmdb',
      },
      watch: false,
    },

    // ============================================
    // Python 服务
    // ============================================
    {
      name: 'analytics-service',
      cwd: './services/analytics-service',
      script: './venv/bin/uvicorn',
      args: 'app.main:app --host 0.0.0.0 --port 60020 --reload',
      interpreter: 'none',
      env: {
        PYTHONPATH: '.',
        CLICKHOUSE_HOST: 'localhost',
        CLICKHOUSE_PORT: 60032,
        CLICKHOUSE_DATABASE: 'lnk_analytics',
        REDIS_URL: 'redis://localhost:60031',
        KAFKA_BROKERS: 'localhost:60033',
      },
      watch: false,
    },
    {
      name: 'datastream-service',
      cwd: './services/datastream-service',
      script: './venv/bin/uvicorn',
      args: 'app.main:app --host 0.0.0.0 --port 60021 --reload',
      interpreter: 'none',
      env: {
        PYTHONPATH: '.',
        KAFKA_BROKERS: 'localhost:60033',
        REDIS_URL: 'redis://localhost:60031',
      },
      watch: false,
    },

    // ============================================
    // 前端服务
    // ============================================
    {
      name: 'user-portal',
      cwd: './frontend/user-portal',
      script: 'npm',
      args: 'run dev',
      env: {
        VITE_USER_SERVICE_URL: 'http://localhost:60002',
        VITE_LINK_SERVICE_URL: 'http://localhost:60003',
        VITE_ANALYTICS_SERVICE_URL: 'http://localhost:60020',
        VITE_QR_SERVICE_URL: 'http://localhost:60005',
      },
      watch: false,
    },
    {
      name: 'console-dashboard',
      cwd: './frontend/console-dashboard',
      script: 'npm',
      args: 'run dev',
      env: {
        VITE_CONSOLE_SERVICE_URL: 'http://localhost:60001',
      },
      watch: false,
    },
  ],
};
