packages:
  # 前端应用
  - "frontend/*"
  # 后端服务（仅 Node.js 服务）
  - "services/user-service"
  - "services/link-service"
  - "services/campaign-service"
  - "services/qr-service"
  - "services/page-service"
  - "services/deeplink-service"
  - "services/notification-service"
  - "services/console-service"
  # 共享包
  - "packages/*"
