import { EXCHANGES, QUEUES } from '@lnk/shared-types';

export const RABBITMQ_CONNECTION = 'RABBITMQ_CONNECTION';
export const RABBITMQ_CHANNEL = 'RABBITMQ_CHANNEL';

// Re-export from shared types
export const NOTIFICATION_EVENTS_EXCHANGE = EXCHANGES.NOTIFICATION_EVENTS;
export const CAMPAIGN_EVENTS_EXCHANGE = EXCHANGES.CAMPAIGN_EVENTS;

export const NOTIFICATION_EMAIL_QUEUE = QUEUES.NOTIFICATION_EMAIL;
export const NOTIFICATION_SLACK_QUEUE = QUEUES.NOTIFICATION_SLACK;
export const NOTIFICATION_WEBHOOK_QUEUE = QUEUES.NOTIFICATION_WEBHOOK;
