import { EXCHANGES, QUEUES } from '@lnk/shared-types';

export const RABBITMQ_CONNECTION = 'RABBITMQ_CONNECTION';
export const RABBITMQ_CHANNEL = 'RABBITMQ_CHANNEL';

// Re-export from shared types
export const LINK_EVENTS_EXCHANGE = EXCHANGES.LINK_EVENTS;
export const CAMPAIGN_EVENTS_EXCHANGE = EXCHANGES.CAMPAIGN_EVENTS;
export const CAMPAIGN_LINK_EVENTS_QUEUE = QUEUES.CAMPAIGN_LINK_EVENTS;
